### ISSUE TITLE
你好，我遇到了段错误，paddlepaddle版本从2.6.1降到2.5.2也没用

### ISSUE THREAD

**Issue by xuquankun** [opendatalab/PDF-Extract-Kit#16]
----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1720767407 (unix time) try "date -d @1720767407" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 13625 (TID 0x7fc896847180) from PID 0 ***]

段错误 (核心已转储)

**Comment by aceliuchanghong** [comment]
同样报错:
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1721780617 (unix time) try "date -d @1721780617" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 878180 (TID 0x7f66f04cc280) from PID 0 ***]

Segmentation fault (core dumped)

**Comment by jorgeolothar** [comment]
I have the same problem. My environment info:

```
sys.platform            linux
Python                  3.10.12 (main, Feb 13 2024, 08:27:59) [GCC 11.4.0]
numpy                   1.26.4
detectron2              0.6 @/home/jorge/.pyenv/versions/PDF-Extract-Kit/lib/python3.10/site-packages/detectron2
Compiler                GCC 9.4
CUDA compiler           CUDA 12.1
detectron2 arch flags   5.0, 6.0, 7.0, 7.5, 8.0, 8.6, 9.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 2.3.1+cu121 @/home/jorge/.pyenv/versions/PDF-Extract-Kit/lib/python3.10/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0,1                 NVIDIA RTX A2000 12GB (arch=8.6)
Driver version          555.99
CUDA_HOME               /usr/local/cuda-11.2
Pillow                  8.4.0
torchvision             0.18.1+cu121 @/home/jorge/.pyenv/versions/PDF-Extract-Kit/lib/python3.10/site-packages/torchvision
torchvision arch flags  5.0, 6.0, 7.0, 7.5, 8.0, 8.6, 9.0
fvcore                  0.1.5.post20221221
iopath                  0.1.9
cv2                     4.6.0

```

**Comment by myhloli** [comment]
@xuquankun @aceliuchanghong @jorgeolothar update paddlepaddle to 3.0.0b1 can solve this problem.


pip install paddlepaddle==3.0.0b1

**Comment by aceliuchanghong** [comment]
> @xuquankun @aceliuchanghong @jorgeolothar update paddlepaddle to 3.0.0b1 can solve this problem.
> 
> 
> pip install paddlepaddle==3.0.0b1

thx
